import '@/styles/globals.css';

import { Navbar } from '@/components/navbar';
import { Inter } from 'next/font/google';
import { mergeClassNames } from '@/lib/utils';
import { Modal } from '@/components/ui';

const font = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={mergeClassNames('bg-black text-gray-100', font.className)}
      >
        <Modal title='Hello' isOpen />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
